### ISSUE TITLE
Cabran Dungeon Roadmap

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/Maps#180]
- [ ] Cabran Falls
- [ ] Yeti Mountain +1 and +2
- [ ] Spectre Lair
- [ ] Desert Town Caves
- [ ] The Shackles -1 and +1
- [ ] Mayhem Caves -1, -2, Roc Lair
- [ ] Salamander Caves
- [ ] Cliff Town
- [ ] Ironfist Castle +1
- [ ] Giant's Outpost
- [ ] Desert Tower -1, +1, and +2
- [ ] The Haunted Cave
- [ ] Cabran Bay
- [ ] Mountain Town
- [ ] Temple of the Snake -1 and -2
- [ ] Swamp Tower +1
- [ ] Temple of the Beetle -1 and -2
- [ ] The Transmuter's Cellar
- [ ] The Gilded Mushroom Forest
- [ ] Mountain of Mayhem +1, +2, +3, +4

Maps that have not been started, coming much later (order not determined):
- [ ] Ironfist Castle -1 and Ironfist Castle +2
- [ ] Mountain Town Store House (Lockers)
- [ ] Ancient Giant Keep (Off of Mountain of Mayhem +3)
- [ ] Undead City and its many branches
- [ ] The second sunken Swamp Tower
- [ ] SW Mountain Dungeon off of Cabran
- [ ] Lich Tower, a very tall structure with the trainer at the top and plenty of traps.
- [ ] Vanidor Lair
